web:
 build: apache
 volumes:
  - ./apache/vhosts:/etc/apache2/sites-enabled
  - ./htdocs:/var/www/html
 ports:
  - "8080:80"
 links:
   - php5.5
   - php5.6
   - php7
php5.5:
 image: php:5.5-fpm
 volumes:
  - ./htdocs:/var/www/html
php5.6:
 image: php:5.6-fpm
 volumes:
  - ./htdocs:/var/www/html
php7:
 image: php:7-fpm
 volumes:
  - ./htdocs:/var/www/html

