web:
 build: apache
 volumes:
  - ./vhosts:/etc/apache2/sites-enabled
  - ./htdocs:/var/www/html
 ports:
  - "8080:80"
 links:
  - php5.5
  - php5.6
  - php7
  - node

php5.5:
 build: php
 dockerfile: Dockerfile-php5.5
 links:
  - db
 volumes:
  - ./htdocs:/var/www/html
php5.6:
 build: php
 dockerfile: Dockerfile-php5.6
 links:
  - db
 volumes:
  - ./htdocs:/var/www/html
php7:
 build: php
 dockerfile: Dockerfile-php7
 links:
  - db
 volumes:
  - ./htdocs:/var/www/html

db:
 image: mysql
 environment:
  - MYSQL_ROOT_PASSWORD=my-secret-pw
 volumes:
  - ./db:/var/lib/mysql
 ports:
  - "3306:3306"

node:
 build: git://github.com/phaldan/docker-nitro.git#master
 volumes:
  - ../my-nitro:/home/yeoman/nitro
 
